# Maintainer: Respire
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=whereami-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Window Switcher for Hyprland"
url="https://github.com/okrespire/whereami"
license=("MIT")
arch=("x86_64")
provides=("whereami")
conflicts=("whereami")
source=("https://github.com/okrespire/whereami/releases/download/v$pkgver/whereami-$pkgver-x86_64.tar.gz")
sha256sums=("9c2a17b10c71efa729ef413fe5c4e130cf675a387f9da9883ae19dbdad05b6c3")

package() {
    install -Dm755 whereami -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
